const state={type:'D-cut bag',shape:'d',colour:'White',colourCss:'#f6f3e9',print:'Single colour print'};
const choices={'Grocery & supermarket':['W / U-cut bag','w','Green','#628458','Single colour print','A durable everyday choice for frequent retail purchases.'],'Pharmacy & medical':['D-cut bag','d','White','#f6f3e9','Single colour print','A clean, practical format for medicine and daily essentials.'],'Apparel & boutique':['Loop-handle bag','loop','Black','#262626','Double colour print','A premium reusable choice that adds value to the purchase.'],'Events & gifting':['Loop-handle bag','loop','Pink','#d4618a','Multi-colour print','A memorable gifting format with room for visual branding.'],'Sweet shop & bakery':['Box bag','box','Yellow','#dbb83d','Double colour print','A structured option that presents packed goods neatly.'],'Promotion & corporate':['D-cut bag','d','Navy','#2f4c73','Single colour print','A scalable, logo-led choice for promotions and events.']};
function updatePreview(){const bag=document.querySelector('#previewBag');bag.className='preview-bag '+state.shape;bag.style.background=state.colourCss;bag.style.color=state.colourCss;document.querySelector('#previewLogo').style.color=state.colour==='White'?'#e9784e':'#fff';document.querySelector('#previewMeta').textContent=state.type+' · '+state.colour+' · '+state.print;document.querySelector('#bagSelect').value=state.type;document.querySelector('#colourInput').value=state.colour;document.querySelector('#printInput').value=state.print}
function chooseBag(type){state.type=type;state.shape=type.startsWith('W')?'w':type.startsWith('Loop')?'loop':type.startsWith('Box')?'box':'d';updatePreview();document.querySelector('#builder').scrollIntoView({behavior:'smooth'})}
document.querySelectorAll('[data-type]').forEach(b=>b.addEventListener('click',()=>chooseBag(b.dataset.type)));
document.querySelectorAll('#typePills button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#typePills button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.type=b.dataset.value;state.shape=b.dataset.class;updatePreview()}));
document.querySelectorAll('#swatches button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#swatches button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.colour=b.dataset.colour;state.colourCss=b.dataset.colour==='Custom colour'?'#f6f3e9':getComputedStyle(b).getPropertyValue('--sw');updatePreview()}));
document.querySelector('#colourReference').addEventListener('input',e=>{if(e.target.value){state.colour=e.target.value;state.colourCss=e.target.value.startsWith('#')?e.target.value:'#f6f3e9';updatePreview()}});
document.querySelectorAll('#printPills button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#printPills button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.print=b.dataset.value;updatePreview()}));
document.querySelectorAll('.market-grid button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.market-grid button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const r=choices[b.dataset.market];state.type=r[0];state.shape=r[1];state.colour=r[2];state.colourCss=r[3];state.print=r[4];document.querySelector('#recommendation p').textContent='Recommended: '+r[0]+' in '+r[2]+', with '+r[4]+'. '+r[5];updatePreview()}));
document.querySelectorAll('.bands button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#qtySelect').value=b.dataset.qty;document.querySelector('#quote').scrollIntoView({behavior:'smooth'});}));
const translations={en:{top:'NON-WOVEN BAGS · CUSTOM COLOURS · BULK ORDERS',hero:'The bag your<br><em>business needs.</em>',markets:'Start with your<br><em>market.</em>',build:'Make it <em>yours.</em>',quote:'Ready when<br><em>you are.</em>'},hi:{top:'नॉन-वोवन बैग · कस्टम रंग · बल्क ऑर्डर',hero:'आपके व्यवसाय को<br><em>चाहिए ऐसा बैग।</em>',markets:'अपने<br><em>मार्केट से शुरू करें।</em>',build:'इसे <em>अपना बनाएँ।</em>',quote:'जब आप<br><em>तैयार हों।</em>'},gu:{top:'નોન-વોવન બેગ · કસ્ટમ રંગ · બલ્ક ઓર્ડર',hero:'તમારા વ્યવસાયને<br><em>જોઈએ એવી બેગ.</em>',markets:'તમારા<br><em>માર્કેટથી શરૂ કરો.</em>',build:'તેને <em>તમારું બનાવો.</em>',quote:'જ્યારે તમે<br><em>તૈયાર હો.</em>'}};
function setLanguage(lang){const t=translations[lang];document.documentElement.lang=lang;document.querySelector('[data-i18n="top"]').textContent=t.top;document.querySelector('[data-i18n="heroTitle"]').innerHTML=t.hero;document.querySelector('[data-i18n="marketsTitle"]').innerHTML=t.markets;document.querySelector('[data-i18n="builderTitle"]').innerHTML=t.build;document.querySelector('[data-i18n="quoteTitle"]').innerHTML=t.quote;document.querySelectorAll('[data-lang]').forEach(x=>x.classList.toggle('active',x.dataset.lang===lang));localStorage.setItem('cbw-lang',lang)}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));
document.querySelector('#quoteForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const f=d.get('artwork');const note=f&&f.name?'%0AArtwork file ready: '+encodeURIComponent(f.name)+' (I will attach it in WhatsApp).':'';const msg='Hello Carry Bags Wala,%0A%0AI need a non-woven bag quote.%0AName: '+encodeURIComponent(d.get('name'))+'%0APhone: '+encodeURIComponent(d.get('phone'))+'%0ABusiness: '+encodeURIComponent(d.get('market'))+'%0ABag: '+encodeURIComponent(d.get('bag'))+'%0AQuantity: '+encodeURIComponent(d.get('quantity'))+'%0AColour: '+encodeURIComponent(d.get('colour'))+'%0APrinting: '+encodeURIComponent(d.get('printing'))+'%0ARequirement: '+encodeURIComponent(d.get('message'))+note;window.open('https://wa.me/919904058078?text='+msg,'_blank','noopener')});
updatePreview();setLanguage(localStorage.getItem('cbw-lang')||'en');
